name: CI
on:
  push:
  pull_request:
jobs:
  simulate_ghdl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup GHDL
        uses: ghdl/setup-ghdl-ci@nightly
      - name: Install tsfpga requirements
        run: pip install -r tsfpga/tsfpga/requirements.txt --pre
      - name: Run simulations
        run: python run.py --vivado-skip -p0
  simulate_nvc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup NVC
        uses: nickg/setup-nvc-ci@v1
        with:
          version: latest
      - name: Install tsfpga requirements
        run: pip install -r tsfpga/tsfpga/requirements.txt --pre
      - name: Run simulations
        run: python run.py --vivado-skip -p0
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: ruff
        run: |
          pip install ruff
          ruff check