name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup GHDL
        uses: ghdl/setup-ghdl-ci@nightly
      - name: Install tsfpga requirements
        run: pip install -r tsfpga/tsfpga/requirements.txt --pre
      - name: Run simulations
        run: python run.py --vivado-skip
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Black
        run: |
          pip install black
          python -m black . --check
