name: CI
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    container: docker://ccfpga/vunit-yosys:latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install tsfpga requirements
        run: pip install -r tsfpga/tsfpga/requirements.txt
      - name: Run simulations
        run: python run.py --vivado-skip
  build:
    runs-on: ubuntu-latest
    container: docker://ccfpga/vunit-yosys:latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install tsfpga requirements
        run: pip install -r tsfpga/tsfpga/requirements.txt
      - name: Synthesize with yosys
        run: python build.py