name: VUnit Tests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    container: docker://ccfpga/vunit-oss:latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install rtoml
        run: pip install rtoml==0.10.0
      - name: Install tsfpga requirements
        run: pip install -r tsfpga/tsfpga/requirements.txt
      - name: Run simulations
        run: python run.py