name: VUnit Tests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    container: docker://ccfpga/vunit-oss:latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install tsfpga requirements
        run: pip install -r tsfpga/tsfpga/requirements.txt
      - name: Run simulations
        run: python run.py