name: VUnit Tests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    container: docker://hdlc/ghdl:yosys
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install tsfpga requirements
        run: python3 -m pip install GitPython rtoml==0.10.0 vunit-hdl hdl-registers
      - name: Run simulations
        run: python run.py